version: '3'

tasks:
  installdeps:
    desc: Install required tools
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go install github.com/cosmtrek/air@latest
  dev:
    desc: Run the application in development mode
    deps:
      - scripts:change_to_dev
      - generate_swagger
      - installdeps
    cmds:
      - air -c .air.toml -- --log-level debug
  build:
    desc: Build the application
    cmds:
      - go build
  scripts:change_to_dev:
    desc: Change the environment to development
    cmds:
      - go run -tags script ./.scripts/change_to_dev.go
  scripts:change_to_prod:
    desc: Change the environment to production
    cmds:
      - go run -tags script ./.scripts/change_to_prod.go
  scripts:delete_docs_dir:
    desc: Delete the docs directory
    cmds:
      - go run -tags script ./.scripts/delete_docs_dir.go
  generate_swagger:
    desc: Generate swagger documentation
    deps:
      - installdeps
      - scripts:delete_docs_dir
    cmds:
      - swag init