version: '3'

tasks:
  installdeps:
    desc: Install required tools
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@latest
      - go install github.com/cosmtrek/air@latest
  dev:
    desc: Run the application in development mode
    deps:
      - scripts:change_to_dev
      - generate_swagger
      - installdeps
    cmds:
      - air -c .air.toml -- --log-level debug
  build:
    desc: Build the application
    cmds:
      - go build
  scripts:change_to_dev:
    desc: Change the environment to development
    cmds:
      - go run -tags script ./.scripts/change_to_dev.go
  scripts:change_to_prod:
    desc: Change the environment to production
    cmds:
      - go run -tags script ./.scripts/change_to_prod.go
  scripts:delete_docs_dir:
    desc: Delete the docs directory
    cmds:
      - go run -tags script ./.scripts/delete_docs_dir.go
  generate_swagger:
    desc: Generate swagger documentation
    deps:
      - installdeps
      - scripts:delete_docs_dir
    cmds:
      - swag init
  generate_api_client_*:
    desc: Generate API client
    deps:
      - generate_swagger
    vars:
        LANG: '{{index .MATCH 0}}'
    cmds:
      - java -jar ./.bin/swagger-codegen-cli.jar generate -l {{.LANG}} -i './docs/swagger.json' -o './_clients/{{.LANG}}' {{.CLI_ARGS}}
#Available languages
#aspnetcore
#csharp
#csharp-dotnet2
#go
#go-server
#dynamic-html
#html
#html2
#java
#jaxrs-cxf-client
#jaxrs-cxf
#inflector
#jaxrs-cxf-cdi
#jaxrs-spec
#jaxrs-jersey
#jaxrs-di
#jaxrs-resteasy-eap
#jaxrs-resteasy
#java-vertx
#micronaut
#spring
#nodejs-server
#openapi
#openapi-yaml
#kotlin-client
#kotlin-server
#php
#python
#python-flask
#r
#ruby
#scala
#scala-akka-http-server
#swift3
#swift4
#swift5
#typescript-angular
#typescript-axios
#typescript-fetch
#javascript